name: R My Package Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: false
        default: 'develop'
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: [ '4.1' ]# , '4.2' ]#, 'devel' ]  # Test on multiple R versions

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          r-version: ${{ matrix.r }}
          extra-packages: |
            any::devtools
            any::rcmdcheck
      - name: Run tests
        run: |
          Rscript -e 'devtools::test()'
      - name: Test coverage
        env:
            COVR_FIX_PARALLEL_MCEXIT: "TRUE"
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          print(getwd())
          print(ls())
          print(file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"))
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
        shell: Rscript {0}

      # - name: Upload test results
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-test-failures
      #     path: ${{ runner.temp }}/package
