name: R My Package Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        r: [ '4.1', '4.2', 'devel' ]  # Test on multiple R versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ runner.os }}-r-library
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "devtools"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        env:
          R_LIBS_USER: ${{ runner.os }}-r-library

      - name: Run tests
        run: |
          Rscript -e 'devtools::test()'
