name: R My Package Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: false
        default: 'main'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        r: [ '4.1' ]# , '4.2', 'devel' ]  # Test on multiple R versions

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          r-version: ${{ matrix.r }}
          extra-packages: |
            any::devtools
            any::rcmdcheck
      - name: Run tests
        run: |
          Rscript -e 'devtools::test()'
